[package]
name = "qemu-riscv-virt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cconsole = {path = "../cconsole" }
uart_16550 = "0.2.16"
spin = "0.9.2"